/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoMusicaRouteImport } from './routes/demo-musica'
import { Route as DescadastrarRouteImport } from './routes/descadastrar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarcaRouteImport } from './routes/marca'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as RetomarRouteImport } from './routes/retomar'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as EditarTokenEdicaoRouteImport } from './routes/editar.$tokenEdicao'
import { Route as EsIndexRouteImport } from './routes/es.index'
import { Route as EsCriarRouteImport } from './routes/es.criar'
import { Route as EsGraciasRouteImport } from './routes/es.gracias'
import { Route as EsLoginRouteImport } from './routes/es.login'
import { Route as PTokenRouteImport } from './routes/p.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMusicaRoute = DemoMusicaRouteImport.update({
  id: '/demo-musica',
  path: '/demo-musica',
  getParentRoute: () => rootRouteImport,
} as any)
const DescadastrarRoute = DescadastrarRouteImport.update({
  id: '/descadastrar',
  path: '/descadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcaRoute = MarcaRouteImport.update({
  id: '/marca',
  path: '/marca',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const RetomarRoute = RetomarRouteImport.update({
  id: '/retomar',
  path: '/retomar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const EditarTokenEdicaoRoute = EditarTokenEdicaoRouteImport.update({
  id: '/editar/$tokenEdicao',
  path: '/editar/$tokenEdicao',
  getParentRoute: () => rootRouteImport,
} as any)
const EsIndexRoute = EsIndexRouteImport.update({
  id: '/es/',
  path: '/es/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsCriarRoute = EsCriarRouteImport.update({
  id: '/es/criar',
  path: '/es/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const EsGraciasRoute = EsGraciasRouteImport.update({
  id: '/es/gracias',
  path: '/es/gracias',
  getParentRoute: () => rootRouteImport,
} as any)
const EsLoginRoute = EsLoginRouteImport.update({
  id: '/es/login',
  path: '/es/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/criar': typeof CriarRoute
  '/dashboard': typeof DashboardRoute
  '/demo-musica': typeof DemoMusicaRoute
  '/descadastrar': typeof DescadastrarRoute
  '/login': typeof LoginRoute
  '/marca': typeof MarcaRoute
  '/obrigado': typeof ObrigadoRoute
  '/recuperar': typeof RecuperarRoute
  '/retomar': typeof RetomarRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/editar/$tokenEdicao': typeof EditarTokenEdicaoRoute
  '/es/criar': typeof EsCriarRoute
  '/es/gracias': typeof EsGraciasRoute
  '/es/login': typeof EsLoginRoute
  '/p/$token': typeof PTokenRoute
  '/es/': typeof EsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/criar': typeof CriarRoute
  '/dashboard': typeof DashboardRoute
  '/demo-musica': typeof DemoMusicaRoute
  '/descadastrar': typeof DescadastrarRoute
  '/login': typeof LoginRoute
  '/marca': typeof MarcaRoute
  '/obrigado': typeof ObrigadoRoute
  '/recuperar': typeof RecuperarRoute
  '/retomar': typeof RetomarRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/editar/$tokenEdicao': typeof EditarTokenEdicaoRoute
  '/es/criar': typeof EsCriarRoute
  '/es/gracias': typeof EsGraciasRoute
  '/es/login': typeof EsLoginRoute
  '/p/$token': typeof PTokenRoute
  '/es': typeof EsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/criar': typeof CriarRoute
  '/dashboard': typeof DashboardRoute
  '/demo-musica': typeof DemoMusicaRoute
  '/descadastrar': typeof DescadastrarRoute
  '/login': typeof LoginRoute
  '/marca': typeof MarcaRoute
  '/obrigado': typeof ObrigadoRoute
  '/recuperar': typeof RecuperarRoute
  '/retomar': typeof RetomarRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/editar/$tokenEdicao': typeof EditarTokenEdicaoRoute
  '/es/criar': typeof EsCriarRoute
  '/es/gracias': typeof EsGraciasRoute
  '/es/login': typeof EsLoginRoute
  '/p/$token': typeof PTokenRoute
  '/es/': typeof EsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/criar'
    | '/dashboard'
    | '/demo-musica'
    | '/descadastrar'
    | '/login'
    | '/marca'
    | '/obrigado'
    | '/recuperar'
    | '/retomar'
    | '/auth/callback'
    | '/editar/$tokenEdicao'
    | '/es/criar'
    | '/es/gracias'
    | '/es/login'
    | '/p/$token'
    | '/es/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/criar'
    | '/dashboard'
    | '/demo-musica'
    | '/descadastrar'
    | '/login'
    | '/marca'
    | '/obrigado'
    | '/recuperar'
    | '/retomar'
    | '/auth/callback'
    | '/editar/$tokenEdicao'
    | '/es/criar'
    | '/es/gracias'
    | '/es/login'
    | '/p/$token'
    | '/es'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/criar'
    | '/dashboard'
    | '/demo-musica'
    | '/descadastrar'
    | '/login'
    | '/marca'
    | '/obrigado'
    | '/recuperar'
    | '/retomar'
    | '/auth/callback'
    | '/editar/$tokenEdicao'
    | '/es/criar'
    | '/es/gracias'
    | '/es/login'
    | '/p/$token'
    | '/es/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CriarRoute: typeof CriarRoute
  DashboardRoute: typeof DashboardRoute
  DemoMusicaRoute: typeof DemoMusicaRoute
  DescadastrarRoute: typeof DescadastrarRoute
  LoginRoute: typeof LoginRoute
  MarcaRoute: typeof MarcaRoute
  ObrigadoRoute: typeof ObrigadoRoute
  RecuperarRoute: typeof RecuperarRoute
  RetomarRoute: typeof RetomarRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EditarTokenEdicaoRoute: typeof EditarTokenEdicaoRoute
  EsCriarRoute: typeof EsCriarRoute
  EsGraciasRoute: typeof EsGraciasRoute
  EsLoginRoute: typeof EsLoginRoute
  PTokenRoute: typeof PTokenRoute
  EsIndexRoute: typeof EsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-musica': {
      id: '/demo-musica'
      path: '/demo-musica'
      fullPath: '/demo-musica'
      preLoaderRoute: typeof DemoMusicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descadastrar': {
      id: '/descadastrar'
      path: '/descadastrar'
      fullPath: '/descadastrar'
      preLoaderRoute: typeof DescadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marca': {
      id: '/marca'
      path: '/marca'
      fullPath: '/marca'
      preLoaderRoute: typeof MarcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retomar': {
      id: '/retomar'
      path: '/retomar'
      fullPath: '/retomar'
      preLoaderRoute: typeof RetomarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editar/$tokenEdicao': {
      id: '/editar/$tokenEdicao'
      path: '/editar/$tokenEdicao'
      fullPath: '/editar/$tokenEdicao'
      preLoaderRoute: typeof EditarTokenEdicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/': {
      id: '/es/'
      path: '/es'
      fullPath: '/es/'
      preLoaderRoute: typeof EsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/criar': {
      id: '/es/criar'
      path: '/es/criar'
      fullPath: '/es/criar'
      preLoaderRoute: typeof EsCriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/gracias': {
      id: '/es/gracias'
      path: '/es/gracias'
      fullPath: '/es/gracias'
      preLoaderRoute: typeof EsGraciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/login': {
      id: '/es/login'
      path: '/es/login'
      fullPath: '/es/login'
      preLoaderRoute: typeof EsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CriarRoute: CriarRoute,
  DashboardRoute: DashboardRoute,
  DemoMusicaRoute: DemoMusicaRoute,
  DescadastrarRoute: DescadastrarRoute,
  LoginRoute: LoginRoute,
  MarcaRoute: MarcaRoute,
  ObrigadoRoute: ObrigadoRoute,
  RecuperarRoute: RecuperarRoute,
  RetomarRoute: RetomarRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EditarTokenEdicaoRoute: EditarTokenEdicaoRoute,
  EsCriarRoute: EsCriarRoute,
  EsGraciasRoute: EsGraciasRoute,
  EsLoginRoute: EsLoginRoute,
  PTokenRoute: PTokenRoute,
  EsIndexRoute: EsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
