/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as DemoMusicaRouteImport } from './routes/demo-musica'
import { Route as MarcaRouteImport } from './routes/marca'
import { Route as EditarTokenEdicaoRouteImport } from './routes/editar.$tokenEdicao'
import { Route as PTokenRouteImport } from './routes/p.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMusicaRoute = DemoMusicaRouteImport.update({
  id: '/demo-musica',
  path: '/demo-musica',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcaRoute = MarcaRouteImport.update({
  id: '/marca',
  path: '/marca',
  getParentRoute: () => rootRouteImport,
} as any)
const EditarTokenEdicaoRoute = EditarTokenEdicaoRouteImport.update({
  id: '/editar/$tokenEdicao',
  path: '/editar/$tokenEdicao',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/criar': typeof CriarRoute
  '/demo-musica': typeof DemoMusicaRoute
  '/marca': typeof MarcaRoute
  '/editar/$tokenEdicao': typeof EditarTokenEdicaoRoute
  '/p/$token': typeof PTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/criar': typeof CriarRoute
  '/demo-musica': typeof DemoMusicaRoute
  '/marca': typeof MarcaRoute
  '/editar/$tokenEdicao': typeof EditarTokenEdicaoRoute
  '/p/$token': typeof PTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/criar': typeof CriarRoute
  '/demo-musica': typeof DemoMusicaRoute
  '/marca': typeof MarcaRoute
  '/editar/$tokenEdicao': typeof EditarTokenEdicaoRoute
  '/p/$token': typeof PTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/criar'
    | '/demo-musica'
    | '/marca'
    | '/editar/$tokenEdicao'
    | '/p/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/criar'
    | '/demo-musica'
    | '/marca'
    | '/editar/$tokenEdicao'
    | '/p/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/criar'
    | '/demo-musica'
    | '/marca'
    | '/editar/$tokenEdicao'
    | '/p/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CriarRoute: typeof CriarRoute
  DemoMusicaRoute: typeof DemoMusicaRoute
  MarcaRoute: typeof MarcaRoute
  EditarTokenEdicaoRoute: typeof EditarTokenEdicaoRoute
  PTokenRoute: typeof PTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-musica': {
      id: '/demo-musica'
      path: '/demo-musica'
      fullPath: '/demo-musica'
      preLoaderRoute: typeof DemoMusicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marca': {
      id: '/marca'
      path: '/marca'
      fullPath: '/marca'
      preLoaderRoute: typeof MarcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editar/$tokenEdicao': {
      id: '/editar/$tokenEdicao'
      path: '/editar/$tokenEdicao'
      fullPath: '/editar/$tokenEdicao'
      preLoaderRoute: typeof EditarTokenEdicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CriarRoute: CriarRoute,
  DemoMusicaRoute: DemoMusicaRoute,
  MarcaRoute: MarcaRoute,
  EditarTokenEdicaoRoute: EditarTokenEdicaoRoute,
  PTokenRoute: PTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
