/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoMusicaRouteImport } from './routes/demo-musica'
import { Route as DescadastrarRouteImport } from './routes/descadastrar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarcaRouteImport } from './routes/marca'
import { Route as MeuQuadroRouteImport } from './routes/meu-quadro'
import { Route as MusicaPersonalizadaParaEsposaRouteImport } from './routes/musica-personalizada-para-esposa'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as RetomarRouteImport } from './routes/retomar'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as EditarTokenEdicaoRouteImport } from './routes/editar.$tokenEdicao'
import { Route as EsIndexRouteImport } from './routes/es.index'
import { Route as EsCriarRouteImport } from './routes/es.criar'
import { Route as EsGraciasRouteImport } from './routes/es.gracias'
import { Route as EsLoginRouteImport } from './routes/es.login'
import { Route as OfertaTokenRouteImport } from './routes/oferta.$token'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as PixReferenciaRouteImport } from './routes/pix.$referencia'
import { Route as QuadroTokenEdicaoRouteImport } from './routes/quadro.$tokenEdicao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMusicaRoute = DemoMusicaRouteImport.update({
  id: '/demo-musica',
  path: '/demo-musica',
  getParentRoute: () => rootRouteImport,
} as any)
const DescadastrarRoute = DescadastrarRouteImport.update({
  id: '/descadastrar',
  path: '/descadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcaRoute = MarcaRouteImport.update({
  id: '/marca',
  path: '/marca',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuQuadroRoute = MeuQuadroRouteImport.update({
  id: '/meu-quadro',
  path: '/meu-quadro',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicaPersonalizadaParaEsposaRoute =
  MusicaPersonalizadaParaEsposaRouteImport.update({
    id: '/musica-personalizada-para-esposa',
    path: '/musica-personalizada-para-esposa',
    getParentRoute: () => rootRouteImport,
  } as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const RetomarRoute = RetomarRouteImport.update({
  id: '/retomar',
  path: '/retomar',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const EditarTokenEdicaoRoute = EditarTokenEdicaoRouteImport.update({
  id: '/editar/$tokenEdicao',
  path: '/editar/$tokenEdicao',
  getParentRoute: () => rootRouteImport,
} as any)
const EsIndexRoute = EsIndexRouteImport.update({
  id: '/es/',
  path: '/es/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsCriarRoute = EsCriarRouteImport.update({
  id: '/es/criar',
  path: '/es/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const EsGraciasRoute = EsGraciasRouteImport.update({
  id: '/es/gracias',
  path: '/es/gracias',
  getParentRoute: () => rootRouteImport,
} as any)
const EsLoginRoute = EsLoginRouteImport.update({
  id: '/es/login',
  path: '/es/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaTokenRoute = OfertaTokenRouteImport.update({
  id: '/oferta/$token',
  path: '/oferta/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PixReferenciaRoute = PixReferenciaRouteImport.update({
  id: '/pix/$referencia',
  path: '/pix/$referencia',
  getParentRoute: () => rootRouteImport,
} as any)
const QuadroTokenEdicaoRoute = QuadroTokenEdicaoRouteImport.update({
  id: '/quadro/$tokenEdicao',
  path: '/quadro/$tokenEdicao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/criar': typeof CriarRoute
  '/dashboard': typeof DashboardRoute
  '/demo-musica': typeof DemoMusicaRoute
  '/descadastrar': typeof DescadastrarRoute
  '/login': typeof LoginRoute
  '/marca': typeof MarcaRoute
  '/meu-quadro': typeof MeuQuadroRoute
  '/musica-personalizada-para-esposa': typeof MusicaPersonalizadaParaEsposaRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar': typeof RecuperarRoute
  '/retomar': typeof RetomarRoute
  '/termos': typeof TermosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/editar/$tokenEdicao': typeof EditarTokenEdicaoRoute
  '/es/criar': typeof EsCriarRoute
  '/es/gracias': typeof EsGraciasRoute
  '/es/login': typeof EsLoginRoute
  '/oferta/$token': typeof OfertaTokenRoute
  '/p/$token': typeof PTokenRoute
  '/pix/$referencia': typeof PixReferenciaRoute
  '/quadro/$tokenEdicao': typeof QuadroTokenEdicaoRoute
  '/es/': typeof EsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/criar': typeof CriarRoute
  '/dashboard': typeof DashboardRoute
  '/demo-musica': typeof DemoMusicaRoute
  '/descadastrar': typeof DescadastrarRoute
  '/login': typeof LoginRoute
  '/marca': typeof MarcaRoute
  '/meu-quadro': typeof MeuQuadroRoute
  '/musica-personalizada-para-esposa': typeof MusicaPersonalizadaParaEsposaRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar': typeof RecuperarRoute
  '/retomar': typeof RetomarRoute
  '/termos': typeof TermosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/editar/$tokenEdicao': typeof EditarTokenEdicaoRoute
  '/es/criar': typeof EsCriarRoute
  '/es/gracias': typeof EsGraciasRoute
  '/es/login': typeof EsLoginRoute
  '/oferta/$token': typeof OfertaTokenRoute
  '/p/$token': typeof PTokenRoute
  '/pix/$referencia': typeof PixReferenciaRoute
  '/quadro/$tokenEdicao': typeof QuadroTokenEdicaoRoute
  '/es': typeof EsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/criar': typeof CriarRoute
  '/dashboard': typeof DashboardRoute
  '/demo-musica': typeof DemoMusicaRoute
  '/descadastrar': typeof DescadastrarRoute
  '/login': typeof LoginRoute
  '/marca': typeof MarcaRoute
  '/meu-quadro': typeof MeuQuadroRoute
  '/musica-personalizada-para-esposa': typeof MusicaPersonalizadaParaEsposaRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar': typeof RecuperarRoute
  '/retomar': typeof RetomarRoute
  '/termos': typeof TermosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/editar/$tokenEdicao': typeof EditarTokenEdicaoRoute
  '/es/criar': typeof EsCriarRoute
  '/es/gracias': typeof EsGraciasRoute
  '/es/login': typeof EsLoginRoute
  '/oferta/$token': typeof OfertaTokenRoute
  '/p/$token': typeof PTokenRoute
  '/pix/$referencia': typeof PixReferenciaRoute
  '/quadro/$tokenEdicao': typeof QuadroTokenEdicaoRoute
  '/es/': typeof EsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/criar'
    | '/dashboard'
    | '/demo-musica'
    | '/descadastrar'
    | '/login'
    | '/marca'
    | '/meu-quadro'
    | '/musica-personalizada-para-esposa'
    | '/obrigado'
    | '/privacidade'
    | '/recuperar'
    | '/retomar'
    | '/termos'
    | '/auth/callback'
    | '/editar/$tokenEdicao'
    | '/es/criar'
    | '/es/gracias'
    | '/es/login'
    | '/oferta/$token'
    | '/p/$token'
    | '/pix/$referencia'
    | '/quadro/$tokenEdicao'
    | '/es/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/criar'
    | '/dashboard'
    | '/demo-musica'
    | '/descadastrar'
    | '/login'
    | '/marca'
    | '/meu-quadro'
    | '/musica-personalizada-para-esposa'
    | '/obrigado'
    | '/privacidade'
    | '/recuperar'
    | '/retomar'
    | '/termos'
    | '/auth/callback'
    | '/editar/$tokenEdicao'
    | '/es/criar'
    | '/es/gracias'
    | '/es/login'
    | '/oferta/$token'
    | '/p/$token'
    | '/pix/$referencia'
    | '/quadro/$tokenEdicao'
    | '/es'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/criar'
    | '/dashboard'
    | '/demo-musica'
    | '/descadastrar'
    | '/login'
    | '/marca'
    | '/meu-quadro'
    | '/musica-personalizada-para-esposa'
    | '/obrigado'
    | '/privacidade'
    | '/recuperar'
    | '/retomar'
    | '/termos'
    | '/auth/callback'
    | '/editar/$tokenEdicao'
    | '/es/criar'
    | '/es/gracias'
    | '/es/login'
    | '/oferta/$token'
    | '/p/$token'
    | '/pix/$referencia'
    | '/quadro/$tokenEdicao'
    | '/es/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CriarRoute: typeof CriarRoute
  DashboardRoute: typeof DashboardRoute
  DemoMusicaRoute: typeof DemoMusicaRoute
  DescadastrarRoute: typeof DescadastrarRoute
  LoginRoute: typeof LoginRoute
  MarcaRoute: typeof MarcaRoute
  MeuQuadroRoute: typeof MeuQuadroRoute
  MusicaPersonalizadaParaEsposaRoute: typeof MusicaPersonalizadaParaEsposaRoute
  ObrigadoRoute: typeof ObrigadoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecuperarRoute: typeof RecuperarRoute
  RetomarRoute: typeof RetomarRoute
  TermosRoute: typeof TermosRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EditarTokenEdicaoRoute: typeof EditarTokenEdicaoRoute
  EsCriarRoute: typeof EsCriarRoute
  EsGraciasRoute: typeof EsGraciasRoute
  EsLoginRoute: typeof EsLoginRoute
  OfertaTokenRoute: typeof OfertaTokenRoute
  PTokenRoute: typeof PTokenRoute
  PixReferenciaRoute: typeof PixReferenciaRoute
  QuadroTokenEdicaoRoute: typeof QuadroTokenEdicaoRoute
  EsIndexRoute: typeof EsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-musica': {
      id: '/demo-musica'
      path: '/demo-musica'
      fullPath: '/demo-musica'
      preLoaderRoute: typeof DemoMusicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descadastrar': {
      id: '/descadastrar'
      path: '/descadastrar'
      fullPath: '/descadastrar'
      preLoaderRoute: typeof DescadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marca': {
      id: '/marca'
      path: '/marca'
      fullPath: '/marca'
      preLoaderRoute: typeof MarcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-quadro': {
      id: '/meu-quadro'
      path: '/meu-quadro'
      fullPath: '/meu-quadro'
      preLoaderRoute: typeof MeuQuadroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musica-personalizada-para-esposa': {
      id: '/musica-personalizada-para-esposa'
      path: '/musica-personalizada-para-esposa'
      fullPath: '/musica-personalizada-para-esposa'
      preLoaderRoute: typeof MusicaPersonalizadaParaEsposaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retomar': {
      id: '/retomar'
      path: '/retomar'
      fullPath: '/retomar'
      preLoaderRoute: typeof RetomarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editar/$tokenEdicao': {
      id: '/editar/$tokenEdicao'
      path: '/editar/$tokenEdicao'
      fullPath: '/editar/$tokenEdicao'
      preLoaderRoute: typeof EditarTokenEdicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/': {
      id: '/es/'
      path: '/es'
      fullPath: '/es/'
      preLoaderRoute: typeof EsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/criar': {
      id: '/es/criar'
      path: '/es/criar'
      fullPath: '/es/criar'
      preLoaderRoute: typeof EsCriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/gracias': {
      id: '/es/gracias'
      path: '/es/gracias'
      fullPath: '/es/gracias'
      preLoaderRoute: typeof EsGraciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/login': {
      id: '/es/login'
      path: '/es/login'
      fullPath: '/es/login'
      preLoaderRoute: typeof EsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta/$token': {
      id: '/oferta/$token'
      path: '/oferta/$token'
      fullPath: '/oferta/$token'
      preLoaderRoute: typeof OfertaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pix/$referencia': {
      id: '/pix/$referencia'
      path: '/pix/$referencia'
      fullPath: '/pix/$referencia'
      preLoaderRoute: typeof PixReferenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quadro/$tokenEdicao': {
      id: '/quadro/$tokenEdicao'
      path: '/quadro/$tokenEdicao'
      fullPath: '/quadro/$tokenEdicao'
      preLoaderRoute: typeof QuadroTokenEdicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CriarRoute: CriarRoute,
  DashboardRoute: DashboardRoute,
  DemoMusicaRoute: DemoMusicaRoute,
  DescadastrarRoute: DescadastrarRoute,
  LoginRoute: LoginRoute,
  MarcaRoute: MarcaRoute,
  MeuQuadroRoute: MeuQuadroRoute,
  MusicaPersonalizadaParaEsposaRoute: MusicaPersonalizadaParaEsposaRoute,
  ObrigadoRoute: ObrigadoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RecuperarRoute: RecuperarRoute,
  RetomarRoute: RetomarRoute,
  TermosRoute: TermosRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EditarTokenEdicaoRoute: EditarTokenEdicaoRoute,
  EsCriarRoute: EsCriarRoute,
  EsGraciasRoute: EsGraciasRoute,
  EsLoginRoute: EsLoginRoute,
  OfertaTokenRoute: OfertaTokenRoute,
  PTokenRoute: PTokenRoute,
  PixReferenciaRoute: PixReferenciaRoute,
  QuadroTokenEdicaoRoute: QuadroTokenEdicaoRoute,
  EsIndexRoute: EsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
