// Os dez artigos da spec §2, na ordem. O validador confere `relacionados`
// contra esta lista (dá pra escrever em levas); o teste de conteúdo exige que
// todos existam.
export const PAUTA = [
  "musica-personalizada-para-mae",
  "musica-personalizada-para-pai",
  "musica-personalizada-para-namorada",
  "homenagem-para-avo",
  "presente-aniversario-de-namoro",
  "presente-bodas-aniversario-de-casamento",
  "presente-de-natal-emocionante",
  "louvor-personalizado",
  "como-fazer-uma-musica-para-alguem",
  "presente-criativo-de-ultima-hora",
  // Leva gospel (03/10/2026): todos com tema "gospel".
  "presente-para-mae-evangelica",
  "presente-para-pai-evangelico",
  "presente-para-pastor",
  "homenagem-para-pastora",
  "musica-gospel-para-casamento",
  "louvor-aniversario-de-casamento",
  "louvor-de-gratidao",
  "louvor-de-testemunho",
  "louvor-para-momento-dificil",
  "presente-de-batismo-evangelico",
  "musica-gospel-de-aniversario",
  "presente-para-amiga-evangelica",
  "presente-de-natal-cristao",
  "presente-para-lider-de-louvor",
  "louvor-para-filho",
  "presente-para-namorada-crista",
  "como-escrever-um-louvor",
  "hino-personalizado",
  "homenagem-dia-das-maes-igreja",
  "louvor-culto-de-acao-de-gracas",
] as const;
